name: darn
version: 1.0.0
author: Kenneth Endfinger <kaendfinger@gmail.com>
description: Build Tool for Dart Project Developers
homepage: https://github.com/DirectMyFile/darn
dependencies:
  args: '>=0.12.0+2 <0.13.0'
  console: '>=1.0.0 <2.0.0'
  quiver: '>=0.18.2 <0.19.0'
executables:
  darn: darn
